### ISSUE TITLE
TypeError: serverRenderer is not a function on initial page load

### ISSUE THREAD

**Issue by klis87** [60frames/webpack-hot-server-middleware#27]
I was getting an error from the title when I started my server and opened my browser before compilation was finished. After compilation was done, everything started to work perfectly. So it seems that ```webpack-dev-middleware``` didn't put serving responses on hold during code compilation, despite the fact my setup was according to the docs.

What helped me was adding ```serverSideRender: true``` to  ```webpack-dev-middleware```, but it was not mentioned in the docs, that's why I am asking, if anyone experienced similar issue? I yes, I could create a PR to mention this in the docs.

**Comment by richardscarrott** [comment]
@klis87 I remember seeing [this line in webpack dev server](https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L41 ) and not really following what could cause that code path so I'm guessing that's what's happening for you?

If you can push up an example repo I'd be able to debug your issue more easily?

In the meantime, as you've discovered the `webpack-dev-middleware` `serverSideRender` option (which really means `alwaysWaitForBuild` and `stickWebpackStatsOnReq`) will fix it because of [this code](https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L27).

Alternatively I think this'd also work:

```
const compiler = webpack(config);
const devMiddleware = webpackDevMiddleware(compiler);
app.use(devMiddleware);
app.use((req, res, next) => {
    devMiddleware.waitUntilValid(() => webpackHotServerMiddleware(req, res, next));
});
```

Which might be what `webpack-hot-server-middleware` will have to do internally if `webpack-dev-middleware` is not waiting for the build for a valid reason.

**Comment by klis87** [comment]
@richardscarrott thanks for your detailed answer. I can see right now why ```serverSideRender: true``` helped me. Now the question is, why ```webpack-dev-middleware``` doesn't wait for webpack to compile,, in my case it doesn't even wait for client code to be compiled, because once I start my server and go to browser I immediately can see this error from the title of this issue.

 I will upload my setup as a package within several days so we could debug this issue. For now, I think ```serverSideRender: true``` is a good workaround.

**Comment by klis87** [comment]
@richardscarrott Apologies it took so long but I have just made an example repo: https://github.com/klis87/webpack-hot-server-middleware-example

Just `yarn install` and `yarn start` and load `localhost:3000` before webpack ends compiling. Of course you could switch `yarn` with `npm` without a problem :)

**Comment by richardscarrott** [comment]
@klis87 Thanks for putting together that repo, I'm planning on taking a look at it this week.

**Comment by klis87** [comment]
@richardscarrott No problem, thanks. Btw, react hot middleware was recently updated but this issue still remains, writing just in case to save you a little time :)

**Comment by richardscarrott** [comment]
@klis87 I've had a look into your example repo and the key difference with my setup is the use of [`publicPath`](https://github.com/klis87/webpack-hot-server-middleware-example/blob/master/src/server.js#L14).

I've confirmed it fails to wait for the compiler because `webpack-dev-middleware` determines the request for '/' is not part of webpack build because it [doesn't include the public path](https://github.com/webpack/webpack-dev-middleware/blob/master/lib/GetFilenameFromUrl.js#L19).

tbh, I'm not really sure why the `publicPath` option exists, I'd have thought the more idiomatic api would be to mount it on the public path, e.g.

```
app.use('/assets/', webpackDevMiddleware());
```

Regardless, I think your `serverSideRender: true` solution is the right way to fix this so it'd be good to document it in the README, probably for all cases (i.e. avoid making the docs complicated and just recommend the use of `serverSideRender: true` always, regardless of publicPath usage).

If you'd like to open a PR to update the README, please do, otherwise let me know and I'll push something up later on.

Also, I'm tempted to send a PR to `webpack-dev-middleware`, aliasing 'serverSideRender' to `alwaysWaitForBuild` just in case we're relying on an implementation detail...

**Comment by klis87** [comment]
@richardscarrott Thanks for your investigation. I just created a pull request - #34 .

I think your PR to `webpack-dev-middleware` is a good idea. I think `serverSideRender` is a confusing name for this option. I am not sure however whether `alwaysWaitForBuild` would be self-explanatory either :) I am just not sure what this option really does under the hood and what it really should mean for the library users.
