### ISSUE TITLE
Access to compiler in serverRenderer

### ISSUE THREAD

**Issue by amangeot** [60frames/webpack-hot-server-middleware#37]
Hello,
first of all, thank you for this awesome library, it's saving me.

I would like to inject data into an html file that is generated from a template, and kept in memory, by html-webpack-plugin. Data to inject could be html metas, preloaded state (it's for a react-redux app), etc.

I read that one way to do it is to access the file in memory, which requires access to the compiler:
```
const filename = path.join(compiler.outputPath, 'index.html')
compiler.outputFileSystem.readFile(filename, (err, result) => {
  // do something
})
```

Is it possible the pass the compiler to the `serverRenderer` function ? Or is there a better way to access webpack ouputs ?

**Comment by amangeot** [comment]
Oh. Sorry just realized you enabled it with serverRendererOptions. I'll paste the code here in case someone's looking for it:
```
app.use(require('webpack-hot-server-middleware')(compiler, {
  serverRendererOptions: { compiler }
}))
```
It would be awesome if you could add the code snippet the description, it makes it easier to read. Maybe by adding a "common example" or something like this. But it's just a suggestion !

**Comment by richardscarrott** [comment]
@amangeot I'm not sure I want to promote passing the compiler to the serverRenderer because I can imagine people relying on it, then realising they don't have it in production, i.e. when serving static files.

Are you conditionally using it in dev vs production?

**Comment by amangeot** [comment]
Yes you're right. I'm passing the compiler in dev environment only, to access the html template generated by `html-webpack-plugin` from Webpack compiler's `outputFileSystem`. 

For production environment, the plan is to read the template directly from the output folder.

The idea is to let html-webpack-plugin inject JS bundles, with hashed names, into the html template, before injecting markup, preloaded state, metas, etc.

It looks like it's working so far. I'm passing the client compiler to the serverRenderer:
`const clientCompiler = compiler.compilers.find(compiler => compiler.name === 'client')`

**Comment by richardscarrott** [comment]
tbh I've never really seen the appeal of the `html-webpack-plugin` as it's not particularly difficult to take the webpack stats and render html but I can see there's at least [4,001 people who beg to differ](https://github.com/jantimon/html-webpack-plugin/stargazers) 😜 

I can't see any issue with the approach you're taking as long as you remember the compiler won't exist in production.

re: docs, I'd be happy to accept a PR updating the README with an example of `serverRendererOptions` but perhaps just passing `{ foo: 'bar' }` rather than the compiler for aforementioned reasons.
