### ISSUE TITLE
Production setup

### ISSUE THREAD

**Issue by wuct** [60frames/webpack-hot-server-middleware#4]
Is there any suggested setup for production?

In my mind, it would be something like:

``` JavaScript
app.use(webpackDevMiddleware(compiler, {
    noInfo: true
}));

if (procsss.env.NODE_ENV !== 'production') {
  app.use(webpackHotServerMiddleware(compiler));
} else {
  app.use((req, res) => {
    const stat = require(dist + '/stat.json')
    const server = require(dist + '/server')
    server(stat)(req, res)
  });
}

app.listen(6060, () => {
    console.log('Server started: http://localhost:6060/');
});
```

**Comment by richardscarrott** [comment]
Hi @wuct -- yes, that's exactly how I do it apart from I only mount `webpackDevMiddleware` in production too, e.g.

```
if (procsss.env.NODE_ENV !== 'production') {
  app.use(webpackDevMiddleware(compiler, {
    noInfo: true
  }));
  app.use(webpackHotServerMiddleware(compiler));
} else {
  app.use((req, res) => {
    const stat = require(dist + '/stat.json')
    const server = require(dist + '/server')
    server(stat)(req, res)
  });
}

app.listen(6060, () => {
    console.log('Server started: http://localhost:6060/');
});
```

You can see my actual implementation of a dev setup [here](https://github.com/60frames/react-boilerplate/blob/master/server/routes/webpack.js) and production [here](https://github.com/60frames/react-boilerplate/blob/master/server/routes/static.js)

Do you think it's worth adding something about this in the docs?

**Comment by wuct** [comment]
@richardscarrott Yes, I think it would be helpful if we provide this info in the README. I would like to create a PR for this. However, as you mentioned [here](https://github.com/webpack/webpack-dev-middleware/pull/118#issuecomment-250696944), we should add `options.serverSideRender` to `webpack-dev-middleware` to prevent it call `next()` too early. Though, the name of the option is confusing. How do you think?

**Comment by richardscarrott** [comment]
@wuct Okay great -- I'm not sure what @SpaceK33z would like to rename [`options.serverSideRender`](https://github.com/webpack/webpack-dev-middleware/pull/118#issuecomment-250696944) to but I suggested `options.exposeStats` although that would mean that we'd be abusing the fact it happens to also force it to wait for the compiler to stabilise due to an implementation detail.

I also suggested having `webpack-dev-middleware` simply *always* wait for the compiler to stabilise but if that isn't an option then I'd be tempted to suggest creating two options, `options.alwaysWaitUntilStable` and  `options.exposeStats` so your [`goNext`](https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L193) function would do something like this:

```
function goNext() {
    if(!options.exposeStats && !options.waitUntilStable) return next();
    ready(function() {
        if (options.exposeStats) {
            res.locals.webpackStats = webpackStats;
        }
        next();
    }, req);
}
```

If that get's changed in `webpack-dev-middleware` then I think it'd be a good idea to update the docs here to reflect that.

**Comment by richardscarrott** [comment]
I've updated the README with production setup docs -- https://github.com/60frames/webpack-hot-server-middleware/tree/feature/readme#production-setup

**Comment by wuct** [comment]
@richardscarrott LGTM. Thanks!
